name: Deploy project in one job
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Execute lint command
        run: | 
          echo "Linting project..."
          npm run lint
      - name: Execute tests
        run: | 
          echo "Testing project..."
          npm run test
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."