name: Deploy project in three sequential jobs

on: 
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: .github\actions
      - name: Lint code
        run: | 
          echo "Linting project..."
          npm run lint
  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: .github/actions
      - name: Execute tests
        run: | 
          echo "Testing project..."
          npm run test
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: .github/actions
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."